return {
	'deviantfero/wpgtk.vim', 
	'scrooloose/nerdcommenter',
	{
		'nvim-telescope/telescope.nvim',tag = '0.1.3',
		dependencies = { 'nvim-lua/plenary.nvim' }
	},
	'github/copilot.vim',
	--'puremourning/vimspector',
	-- 'davidhalter/jedi-vim',
	--'folke/zen-mode.nvim',
	--'Yggdroot/indentLine',
	--'rebelot/kanagawa.nvim',
	--'AlexvZyl/nordic.nvim',
	-- 'ctrlpvim/ctrlp.vim',
	--'jpalardy/vim-slime',
	--'hanschen/vim-ipython-cell',
	--'junegunn/vim-easy-align',
	--'ottersome/vim-pandoc-markdown-preview',
	--'junegunn/fzf.vim',
	--'yuttie/comfortable-motion.vim',
	--'lervag/vimtex',
	--'xuhdev/vim-latex-live-preview',
	-- 'junegunn/goyo.vim',
	--'junegunn/limelight.vim',
	--'scrooloose/nerdtree',
	--'vim-airline/vim-airline',
	--'vim-airline/vim-airline-themes',
	--'tpope/vim-fugitive',
	--'honza/vim-snippets',
	--'chrisbra/Colorizer',
	--{'neoclide/coc.nvim', branch = 'release'},
	--'pangloss/vim-javascript',
	--'leafgarland/typescript-vim',
	--'peitalin/vim-jsx-typescript',
	--'styled-components/vim-styled-components', { 'branch': 'main', }
	--'jparise/vim-graphql',
}
